//! JavaScript (ES2022) code generator for IndexLanguage.

use crate::ast::*;

pub fn emit(program: &Program) -> String {
    let mut g = Gen {
        out: String::new(),
        indent: 0,
    };
    g.line("// Generated by the IndexLanguage compiler (il).");
    g.line("\"use strict\";");
    g.line("const print = (...args) => console.log(...args);");
    g.newline();
    for item in &program.items {
        g.stmt(item);
    }
    g.out
}

struct Gen {
    out: String,
    indent: usize,
}

impl Gen {
    fn pad(&mut self) {
        for _ in 0..self.indent {
            self.out.push_str("  ");
        }
    }

    fn line(&mut self, s: &str) {
        self.pad();
        self.out.push_str(s);
        self.out.push('\n');
    }

    fn newline(&mut self) {
        self.out.push('\n');
    }

    fn stmt(&mut self, stmt: &Stmt) {
        match stmt {
            Stmt::Fn(f) => {
                let params = f
                    .params
                    .iter()
                    .map(|p| p.name.clone())
                    .collect::<Vec<_>>()
                    .join(", ");
                self.line(&format!("function {}({}) {{", f.name, params));
                self.indent += 1;
                for s in &f.body {
                    self.stmt(s);
                }
                self.indent -= 1;
                self.line("}");
                self.newline();
            }
            Stmt::Let {
                is_const,
                name,
                init,
                ..
            } => {
                let kw = if *is_const { "const" } else { "let" };
                let value = self.expr(init);
                self.line(&format!("{} {} = {};", kw, name, value));
            }
            Stmt::Return { value, .. } => match value {
                Some(e) => {
                    let v = self.expr(e);
                    self.line(&format!("return {};", v));
                }
                None => self.line("return;"),
            },
            Stmt::If {
                cond,
                then_branch,
                else_branch,
            } => {
                let c = self.expr(cond);
                self.line(&format!("if ({}) {{", c));
                self.indent += 1;
                for s in then_branch {
                    self.stmt(s);
                }
                self.indent -= 1;
                match else_branch {
                    None => self.line("}"),
                    Some(else_b) => {
                        self.line("} else {");
                        self.indent += 1;
                        for s in else_b {
                            self.stmt(s);
                        }
                        self.indent -= 1;
                        self.line("}");
                    }
                }
            }
            Stmt::While { cond, body } => {
                let c = self.expr(cond);
                self.line(&format!("while ({}) {{", c));
                self.indent += 1;
                for s in body {
                    self.stmt(s);
                }
                self.indent -= 1;
                self.line("}");
            }
            Stmt::Expr(e) => {
                let v = self.expr(e);
                self.line(&format!("{};", v));
            }
            Stmt::Block(stmts) => {
                self.line("{");
                self.indent += 1;
                for s in stmts {
                    self.stmt(s);
                }
                self.indent -= 1;
                self.line("}");
            }
        }
    }

    fn expr(&self, expr: &Expr) -> String {
        match expr {
            Expr::Number(n) => {
                if n.fract() == 0.0 && n.is_finite() {
                    format!("{}", *n as i64)
                } else {
                    format!("{}", n)
                }
            }
            Expr::Str(s) => json_string(s),
            Expr::Bool(b) => b.to_string(),
            Expr::Ident(name, _) => name.clone(),
            Expr::Array(elems, _) => {
                let parts: Vec<String> = elems.iter().map(|e| self.expr(e)).collect();
                format!("[{}]", parts.join(", "))
            }
            Expr::Unary { op, expr, .. } => format!("{}{}", op, self.expr(expr)),
            Expr::Binary {
                op, left, right, ..
            } => format!("({} {} {})", self.expr(left), op, self.expr(right)),
            Expr::Assign { name, value, .. } => format!("{} = {}", name, self.expr(value)),
            Expr::Call { callee, args, .. } => {
                let a: Vec<String> = args.iter().map(|e| self.expr(e)).collect();
                format!("{}({})", self.expr(callee), a.join(", "))
            }
            Expr::Index { target, index, .. } => {
                format!("{}[{}]", self.expr(target), self.expr(index))
            }
            Expr::Member { target, name, .. } => format!("{}.{}", self.expr(target), name),
        }
    }
}

fn json_string(s: &str) -> String {
    let mut out = String::from("\"");
    for ch in s.chars() {
        match ch {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\t' => out.push_str("\\t"),
            '\r' => out.push_str("\\r"),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}
